### ISSUE TITLE
UI: Refine Tabular Total  / Footer Columns

### ISSUE THREAD

**Issue by FatalMerlin** [ArkanisCorporation/ArkanisOverlay#280]
1. Make global totals stand out more by making them `surface` colored
2. Add `Global` label to the global total row
3. Add `Local` label to the local total row

@ 1.
```css
tfoot td.footer-cell.mud-table-cell {
    background-color: var(--mud-palette-surface);
}
```

@ 2.
```css
tbody tr.mud-table-row td.mud-table-cell.footer-cell:first-child:before {
    content: "Local";
}
```

@ 3.
```css
tfoot tr.mud-table-row td.mud-table-cell.footer-cell:first-child:before {
    content: "Global";
}
```
